<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="12471" started-at="2022-06-19T01:54:41 IDT" finished-at="2022-06-19T01:54:54 IDT">
    <groups>
    </groups>
    <test name="Test" duration-ms="12471" started-at="2022-06-19T01:54:41 IDT" finished-at="2022-06-19T01:54:54 IDT">
      <class name="saucedemo.com.RunTests.LoginTestNG">
        <test-method status="PASS" signature="setup()[pri:0, instance:saucedemo.com.RunTests.LoginTestNG@58c1670b]" name="setup" is-config="true" duration-ms="4715" started-at="2022-06-19T01:54:41 IDT" finished-at="2022-06-19T01:54:46 IDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="tc_01_login()[pri:0, instance:saucedemo.com.RunTests.LoginTestNG@58c1670b]" name="tc_01_login" duration-ms="2340" started-at="2022-06-19T01:54:46 IDT" finished-at="2022-06-19T01:54:48 IDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc_01_login -->
        <test-method status="PASS" signature="tc_02_login()[pri:0, instance:saucedemo.com.RunTests.LoginTestNG@58c1670b]" name="tc_02_login" duration-ms="2258" started-at="2022-06-19T01:54:48 IDT" finished-at="2022-06-19T01:54:50 IDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc_02_login -->
        <test-method status="FAIL" signature="tc_03_login()[pri:0, instance:saucedemo.com.RunTests.LoginTestNG@58c1670b]" name="tc_03_login" duration-ms="187" started-at="2022-06-19T01:54:50 IDT" finished-at="2022-06-19T01:54:51 IDT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Epic sadface: Password is incorrect] but found [Epic sadface: Username and password do not match any user in this service]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Epic sadface: Password is incorrect] but found [Epic sadface: Username and password do not match any user in this service]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at saucedemo.com.RunTests.LoginTestNG.tc_03_login(LoginTestNG.java:81)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:284)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:119)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc_03_login -->
        <test-method status="PASS" signature="tc_04_login()[pri:0, instance:saucedemo.com.RunTests.LoginTestNG@58c1670b]" name="tc_04_login" duration-ms="2270" started-at="2022-06-19T01:54:51 IDT" finished-at="2022-06-19T01:54:53 IDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc_04_login -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:saucedemo.com.RunTests.LoginTestNG@58c1670b]" name="tearDown" is-config="true" duration-ms="648" started-at="2022-06-19T01:54:53 IDT" finished-at="2022-06-19T01:54:54 IDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- saucedemo.com.RunTests.LoginTestNG -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
