<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-06-19T01:56:10 IDT" name="Default suite" finished-at="2022-06-19T01:56:21 IDT" duration-ms="10735">
    <groups>
    </groups>
    <test started-at="2022-06-19T01:56:10 IDT" name="Default test" finished-at="2022-06-19T01:56:21 IDT" duration-ms="10735">
      <class name="saucedemo.com.RunTests.LoginTestNG">
        <test-method is-config="true" signature="setup()[pri:0, instance:saucedemo.com.RunTests.LoginTestNG@54e1c68b]" started-at="2022-06-19T01:56:10 IDT" name="setup" finished-at="2022-06-19T01:56:14 IDT" duration-ms="3461" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="tc_01_login()[pri:0, instance:saucedemo.com.RunTests.LoginTestNG@54e1c68b]" started-at="2022-06-19T01:56:14 IDT" name="tc_01_login" finished-at="2022-06-19T01:56:16 IDT" duration-ms="2393" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc_01_login -->
        <test-method signature="tc_02_login()[pri:0, instance:saucedemo.com.RunTests.LoginTestNG@54e1c68b]" started-at="2022-06-19T01:56:16 IDT" name="tc_02_login" finished-at="2022-06-19T01:56:19 IDT" duration-ms="2260" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc_02_login -->
        <test-method signature="tc_03_login()[pri:0, instance:saucedemo.com.RunTests.LoginTestNG@54e1c68b]" started-at="2022-06-19T01:56:19 IDT" name="tc_03_login" finished-at="2022-06-19T01:56:19 IDT" duration-ms="205" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Epic sadface: Password is incorrect] but found [Epic sadface: Username and password do not match any user in this service]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Epic sadface: Password is incorrect] but found [Epic sadface: Username and password do not match any user in this service]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at saucedemo.com.RunTests.LoginTestNG.tc_03_login(LoginTestNG.java:81)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc_03_login -->
        <test-method signature="tc_04_login()[pri:0, instance:saucedemo.com.RunTests.LoginTestNG@54e1c68b]" started-at="2022-06-19T01:56:19 IDT" name="tc_04_login" finished-at="2022-06-19T01:56:21 IDT" duration-ms="2253" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc_04_login -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:saucedemo.com.RunTests.LoginTestNG@54e1c68b]" started-at="2022-06-19T01:56:21 IDT" name="tearDown" finished-at="2022-06-19T01:56:21 IDT" duration-ms="124" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- saucedemo.com.RunTests.LoginTestNG -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
